### ISSUE TITLE
Failing Jenkins tests for PFI

### ISSUE THREAD

**Issue by GoldenBadger** [CPSSD/paranoid#75]
Jenkins is up and running, and has faling tests for `github.com/cpssd/paranoid/pfi`. The tests rely on a binary being present which is not generated by the tests and must be created by the tester. This is bad practice and should be changed. The following is a snippet of the test output:

```
2015/10/29 12:54:07 Error running pfs command : exec: "pfs": executable file not found in $PATH
exit status 1
touch: cannot touch ‘/tmp/pfiTestMountPoint/helloworld.txt’: Software caused connection abort
ls: cannot access /tmp/pfiTestMountPoint: Transport endpoint is not connected
cat: /tmp/pfiTestMountPoint/helloworld.txt: Transport endpoint is not connected
--- FAIL: TestFuseUsage (3.03s)
    main_test.go:31: Pfs setup failed : exec: "pfs": executable file not found in $PATH
    main_test.go:45: Error running touch : exit status 1
    main_test.go:52: Error running ls :  exit status 2
    main_test.go:56: ls returned incorrect result
    main_test.go:75: Error writing to pfs : exec: "pfs": executable file not found in $PATH
    main_test.go:83: Error running cat command : exit status 1
    main_test.go:86: Unexpected output from cat command
FAIL
FAIL    github.com/cpssd/paranoid/pfi   3.052s
```

Steps to reproduce:
1. Clone the repo, making sure you do not have any paranoid binaries in your `$GOPATH/bin`.
2. Run `go test ./...` from the repo root.
